version: '3.5'

networks:
  fakes3-network:

services:
  fakes3:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    command: "bash -c 'while true; do sleep 2; done'"
    networks:
      fakes3-network:
    logging: &default-logging-options
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
